plugins {
	id 'net.fabricmc.fabric-loom'
}

base {
	archivesName = "yg-drops"
}

loom {
	mods {
		"yg_drops" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	// 依赖 yg-core 基础库（类会一起打进本包 jar）
	implementation project(':core')
}
