plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

base {
	archivesName = "randomdrops-mobs"
}

loom {
	mods {
		"randomdrops-mobs" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	// 生物改变模块依赖核心框架
	implementation project(':core')
}

java {
	withSourcesJar()
}

processResources {
	def ver = project.version
	inputs.property "version", ver
	filesMatching("fabric.mod.json") {
		expand "version": ver
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}
